In [1]:
import numpy as np

In [11]:
def doMathWithNumpy():
    return np.array([5]) * np.array([5])

def doMathWithoutNumpy():
    return 5 * 5

In [12]:
%timeit doMathWithoutNumpy()

50.6 ns ± 0.789 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [13]:
%timeit doMathWithNumpy()

1.82 µs ± 35.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [14]:
v = np.array([1,2,3,4])

In [28]:
v.reshape(4, 1).shape == v[:, None].shape

True

In [35]:
values = [1,2,3,4,5]
values2 = np.array(values)

In [32]:
%%timeit
for i in range(len(values)):
    values[i] += 5

570 ns ± 15.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [43]:
values2 *= 0

In [44]:
values2

array([0, 0, 0, 0, 0])

In [45]:
M = v.reshape(2, 2)

In [46]:
M

array([[1, 2],
       [3, 4]])

In [47]:
M*M

array([[ 1,  4],
       [ 9, 16]])

In [48]:
np.matmul(M, M)

array([[ 7, 10],
       [15, 22]])

In [50]:
v.mean()

2.5