# PyTorch Playground

In [19]:
import torch, torchvision
import numpy as np

In [4]:
data = [[2, 4], [5, 6]]
x_data = torch.tensor(data)
x_data_np = np.array(data)

In [18]:
x_data

tensor([[2, 4],
        [5, 6]])

In [11]:
torch.cuda.is_available()

False

In [17]:
x_data.add(4)

tensor([[ 6,  8],
        [ 9, 10]])

## Automatic Differentiation Playground

In [28]:
model = torchvision.models.resnet18(pretrained=True)
data = torch.rand(1, 3, 64, 64)
labels = torch.rand(1, 1000)

In [29]:
prediction = model(data)

In [30]:
loss = (prediction - labels).sum()
loss.backward()

In [32]:
optim = torch.optim.SGD(model.parameters(), lr=1e-2, momentum=.9)

In [34]:
optim.step()

In [43]:
# Differentiation in Autograd
a = torch.tensor([2.], requires_grad=True)
b = torch.tensor([6.], requires_grad=True)

In [44]:
Q = 3*a**3 - b**2

In [47]:
external_grad = torch.tensor([1.])
Q.backward(gradient=external_grad)

In [48]:
b.grad

tensor([-12.])

In [49]:
a.grad

tensor([36.])